### ISSUE TITLE
Subpage with the list of monitored blogs

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#289]
It would be nice to have a subpage with the list of monitored blogs:
 - link, author name and the number of blog posts in last 3months and in last 6 months divided into personal/company/video channels.

**Comment by ajurasz** [comment]
@tdziurko I would like to work on this but before I will start a work it would be a good idea to agree on display concept. Do we want these channels/sections to be pageable or this will be one long page?

If one long page is not preferred then we can display pageable list withing each channel/section or use [tabs](http://getbootstrap.com/javascript/#tabs) and then not use a pageable list in them (or use them after all?)

**Comment by tdziurko** [comment]
Currently we have 185 active (not dead) blogs, so I think it would be extra cool to have it load lazily and load more when user scrolls down (like a Twitter stream). 
I am not sure how we should display company blogs and video channels, maybe as a separate pages accesible using tabs. So user will go following path:
1. User enters main page and sees blogs link at the top of the application.
2. User enters blogs page and sees list of personal blogs. At the top of this page (below main navigation bar) there are bookmarkable links to the company blogs page and video channels page.
3. Each blog is a link to another sub-page with a list blog entries.

WDYT?

**Comment by ajurasz** [comment]
I think I'm very close to the flow you proposed:

![image](https://cloud.githubusercontent.com/assets/3949308/26765270/d79f8922-4978-11e7-9d2a-0b03d5e442e5.png)

Still to be done:
- [ ] infinite scroll instead of standard pagination 
- [ ] tabs should use bookmarkable links 
- [ ] subpage with list of blog entires

**Comment by tdziurko** [comment]
Looks good :) Maybe I try to seegrid design instead of tables that are better option for backend/admin sections of application :)

**Comment by ajurasz** [comment]
@tdziurko last item to implement is to replace tables with a grid. I just want to check if my understanding of this is correct. You want to replace standard HTML table with formatted `div`s using bootstrap `row` and `col` classes? And then if it comes to the header of this grid we leave HTML table with just a header?

You can also post some link with a web page with similar grid so that I know what to do :)

**Comment by tdziurko** [comment]
What I had in mind that table design is more for backoffice, so it would look better to use something less formal, something close to listing presented at home page or issue page:

    <h1>Monitorowane blogi</h1>
    <div>w nawiasach liczba postów w ostatnich 3 i 6 miesiącach</div
     
    http://something.com by Janusz Blogowania (12/24)
    http://something.com by Janina Blogowania (2/23)
    http://something.com by Ryszard Programowania (15/22)

**Comment by ajurasz** [comment]
Oh, I see. Thx.
