### ISSUE TITLE
Architecture cleanup - discussion

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#326]
I am aware that currently architecture of jvm-bloggers is a small mess, not a big one but still :) There are many places where data is modified and it's hard to understand what is going on.

That is why I would like to discuss introducing something close to `CQRS` architecture with following conventions:

1. All `writes` are done via `Commands` and `CommandPublisher` class.
2. Normal writes are executed synchronously using `CommandHandlers` created 1 to 1 to each `Command`, when we need an async we use Akka actors, but still they are hidden behind `CommandPublisher` and `CommandHandlers`  so there is no way to interact with Actors in other way.
3. For a simplicity we still have one database for both writes and reads.
4. Reads are done via `Query` objects that are created for each use-case. e.g. `PublishedNewsletterIssueQuery`. Queries return immutable `DTOs`.
5. `DTOs` are using domain keys instead of `Long` as IDs, so it's easier to understand what each 'id' value passed to method is doing. For example we use `BlogPostId` to execute `ApproveBlogPostCommand` or `NewsletterIssueNumber` to retrieve `PublishedNewsletterIssue` DTO that will be later on displayed to the user.

Wicket part:

6. Each `Page` has corresponding class. e.g `LoginPageSomething` that is the only point when interaction between view and the rest of the system can occur.
7. Naming convention: For `NewsletterIssuePage` it could be either:
   - `NewsletterIssuePageHandler` (name could class with all `CommandHandlers`)
   - `NewsletterIssuePageBackingBean`
   - `NewsletterIssuePageBean`
This is to be discussed

8. This way each Page will have only one dependency, its `PageHandler`/`BackingBean`/`Bean`
9. Each backing bean in most cases will contain injected `CommandPublisher` instance and some (1 or more) `Query` objects to fetch needed data from the system.

This is a proposed approach and a base for a discussion so please share your thoughts.

**Comment by airborn** [comment]
Do we have any minimal example of this? I've seen your `CQRS-1` branch yesterday, but it is hard to read due to many additional changes. 

Questions:

1. Are we talking about database `writes` and `reads` or all `IO` in general?
1. `DTO` are often 1:1 copy of domain objects. In my opinion to keep things simple we should avoid this everywhere that it is feasible
1. Domain keys are very good point. Question is will we find domain keys for each entity? Should we also consider dropping  `jsonId` from json files at this point?
1. For naming convention I'd suggest `NewsletterIssuePagePresenter` or even `NewsletterIssuePresenter`

In general the whole idea looks good. I'am a little bit afraid that this will introduce a lot of noise in the project, but all in all i think that it is worth trying.

**Comment by tdziurko** [comment]
Q: Are we talking about `database writes` and `reads` or all `IO` in general?
A: I thought mostly about `database writes`. Other IO operations are mostly `rss` fetching via HTTP and it's triggered as asynchronous operations (via schedulers or a button in admin panel). This part of logic should fit somehow into CQRS approach too, but I haven't come up with any concrete solution to this.

Q: DTOs are often 1:1 copy of domain objects. In my opinion to keep things simple we should avoid this everywhere that it is feasible
A: If we aim at small/dedicated `Query` services, we should end with `DTOs` being only a part of original entity or sometimes an extract from two ore more different entities. So this shouldn't be a problem.

Q: Domain keys are very good point. Question is will we find domain keys for each entity? Should we also consider dropping jsonId from json files at this point?
A: Dropping `jsonId' is planned, there is even a task for this. For domain keys for some classes we will have a more "business" key like `NewsletterIssueNumber`, but for some simpler cases we will have a `BlogPostId` wrapping only a primary key, but this will improve readability of all methods where we currently pass some `Long` as some ID. After this change developer won't be able to pass any id, it would have to be exactly `BlogPostId` object, not any `Long`

Idea: For naming convention I'd suggest NewsletterIssuePagePresenter or even NewsletterIssuePresenter
A: Cool, sounds good as long as we agree of something and use it consistently.

**Comment by mchmielarz** [comment]
@airborn I'm not so convinced with `Presenter` naming since such class has a task of providing data to a given page. For me `NewsletterIssuePageBackingBean` or `NewsletterIssuePageDataProvider` sounds good enough. However, this is just an opinion about naming conventions. When it comes to the whole idea, all sounds good.

**Comment by goostleek** [comment]
@airborn 

> A: Dropping jsonId is planned, there is even a task for this.

It's worth to mention we had a [discussion about it on our Slack channel](https://jvm-bloggers.slack.com/archives/general/p1479932071000023)  to let the others know the background behind conclusions we made.
