### ISSUE TITLE
Post newsletter on Twitter

### ISSUE THREAD

**Issue by mchmielarz** [jvm-bloggers/jvm-bloggers#360]
When we create a new newsletter, we should also post information about it on Twitter.

Short info with link to the issue should be enough, I guess.

**Comment by tdziurko** [comment]
For start let it me `Witajcie, najnowsze wydanie #<number> jest już online - <link>`

As a next step it would be cool to have randomly added 1-3 twitter handles of authors included in given issue: `Wydanie #<number> jest już online, a w nim wpisy od <randomTwitterHandle1>, <randomTwitterHandle2>, <randomTwitterHandle3>`, because this nicely increase tweet visibility (people tend to retweet tweets when they are mentioned) :)

**Comment by tdziurko** [comment]
Done :)
