### ISSUE TITLE
Cannot add new Varia

### ISSUE THREAD

**Issue by Koziolek** [jvm-bloggers/jvm-bloggers#542]
After filling add Varia form and clicking „Wyślij” button I get error:

```
Internal error
Return to home page
```

form content:
HTTPS://WWW.MEETUP.COM/PL-PL/WROCLAWJUG/EVENTS/263621680/

WROCAŁAW JUG

WROCŁAW JUG, W ZWIĄZKU ZE ZMIANAMI W API MEETUP.COM, OGŁOSIŁ KONKURS NA NOWE NARZĘDZIE DO LOSOWANIA NAGRÓD NA NASZYCH SPOTKANIACH. DO WYGRANIA LICENCJA NA INTELLIJ.

**Comment by tdziurko** [comment]
Either column for url or message is too short or validation fails for some strange reason.

**Comment by mtszpater** [comment]
I can take it.

**Comment by mtszpater** [comment]
If URL was really looks like that:
```
HTTPS://WWW.MEETUP.COM/PL-PL/WROCLAWJUG/EVENTS/263621680/
```

then URL Validator attached to that field rejected that because URL should starts only with: 
```
"http", "https"
```

Whole form has property:
```text-transform: uppercase;```

but if you take that url, change **HTTPS** to **https** (for example paste that url from somewhere) then it will be sent correctly. 

I added that URL can be in uppercase.

**Comment by tdziurko** [comment]
Fixed
